### ISSUE TITLE
Improved BLU Selection

### ISSUE THREAD

**Issue by caxanga334** [caxanga334/tf-hideandseek#2]
Improve how the plugins select players to BLU team.

## Current Behavior
Players are randomly selected to start on BLU, only ignoring players who started on BLU last round.

## New Behavior
Players who are selected are excluded from the selection, once all players have been selected the plugins reset.

## TO-DO

- [x] Store who played on BLU
- [x] Better random selection code
- [x] Test the new code
